### ISSUE TITLE
Mismatched number of exceptions of NonbondedForce and MPID Force on CUDA platform

### ISSUE THREAD

**Issue by wwilla7** [andysim/MPIDOpenMMPlugin#3]
[butane.zip](https://github.com/andysim/MPIDOpenMMPlugin/files/6474602/butane.zip)
Hi, 

I am trying to test the MPID plugin on a molecule (butane) other than the example ethane, but ran into the issue ```simtk.openmm.OpenMMException: All Forces must have identical exceptions``` on `CUDA` platform. I have attached all files I used in a zip file to this issue.

I installed the MPID plugin with conda using the following commands:

```
conda create -n mpid-test openmm=7.5 cudatoolkit=10.1 swig mdtraj -c conda-forge -y
conda activate mpid-test
export OPENMM_INSTALL_DIR=~/anaconda3/envs/mpid-test

module load cuda/10.1
module load cmake
module load gcc

cd $MPID_PATH/MPIDOpenMMPlugin
mkdir build
cd build
CXX=g++ cmake .. -DCMAKE_INSTALL_PREFIX=$OPENMM_INSTALL_DIR -DPYTHON_EXECUTABLE=`which python` -DOPENMM_DIR=$OPENMM_INSTALL_DIR -DCMAKE_CXX_FLAGS='-std=c++11'
make -j 4
make test
make install
make PythonInstall
```
5 out of 5 tests passed, and I was able to run the example `run_ethane.py` without any errors.

Then, I built the molecule butane and obtained a CHARMM Force Field file `molecule.str` from [CGenFF](https://cgenff.umaryland.edu/), and then created the OpenMM style force field file `molecule.xml` with ParmEd along with some manual modification to work with `MPID plugin`.

Finally, I created the `molecule.pdb` input file with OpenMM, and ran a plain MD in vacuum with script `run_mpid_cuda.py`. I was able to create a system with `MPID Force` and saved it as `system_vac.xml`. However, I ran into the following exception when creating an "OpenMM simulation", and I couldn't find the number of exceptions in the `MPID Force`:
```
  File "/home/wwilla/data/issues/run_mpid.py", line 57, in <module>
    simulation = Simulation(pdb.topology, system, integrator, platform, properties)
  File "/home/wwilla/anaconda3/envs/mpid-test/lib/python3.9/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/wwilla/anaconda3/envs/mpid-test/lib/python3.9/site-packages/simtk/openmm/openmm.py", line 6946, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
simtk.openmm.OpenMMException: All Forces must have identical exceptions
```

On the other hand, the simulation didn't throw any issues when I tested the same input files on the CPU platform with script `run_mpid_cpu.py`. 

I am not very familiar with the `MPID Force` and the corresponding CUDA code, so I am wondering if it's a known issue or anything. Thank you very much for looking into this.

**Comment by andysim** [comment]
Sorry for the delay in figuring this out, and thanks very much for the detailed bug report.  Please feel free to reopen if you have any more problems.

**Comment by wwilla7** [comment]
Thanks very much for looking into this!
